### PR TITLE
Krithika popup

### PR DESCRIPTION
**Pull request by krithikasekhar**
1. Added popup feature in view deals page.
2. Add to cart button should route to Shopping cart page---route not added

### CODE REVIEW

**Comment by cyan33** [comment]
Good stuff Krishna! Could you please do `git pull` and resolve the conflicts?

Also, it would be great if you provide some screen shot about the popup and view-deals. 😄

**Comment by krithikasekhar** [comment]
Hey it would not be possible for me to work on it till around 5.30. Is that
fine? Or you can go ahead and make the necessary changes

P.s it's Krithika, not Krishna 😛

**Comment by cyan33** [comment]
Sorry Krithika I'm bad at remembering people's name 😢 .
No worries, we can wait until you have time to work on this.

**Comment by krithikasekhar** [comment]
Okay cool!

**Comment by krithikasekhar** [comment]
@cyan33  Resolved the merge conflicts!

**Comment by cyan33** [comment]
Could you please also provide a screenshot of your features? 😄

**Comment by krithikasekhar** [comment]
@cyan33 I have uploaded the screenshot in slack just as you requested

**Pull request merged**
